# Dockerfile.dev
# Use an official Node.js runtime as the base image
FROM node:lts-alpine

RUN corepack enable

# Set the working directory in the container to /app
WORKDIR /app

# Bundle app source inside the docker image
COPY . .

# Install any needed packages specified in package.json
RUN yarn install

# Make port 4321 available to the world outside this container
EXPOSE 4321

# Run the command to start the app in development mode with hot reloading
CMD ["yarn", "run", "dev"]