version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    # environment:
    #   DATABASE_URL: postgres://postgres:password@db:5432/your_database

  frontend:
    build: ./frontend
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  caddy:
    image: caddy:latest
    volumes:
      - ./caddy_config:/etc/caddy
      - ./frontend/public:/public
    ports:
      - "80:80"
    command: caddy run --config /etc/caddy/Caddyfile
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
