# Dockerfile.dev
# Start from the cosmtrek/air base image
FROM cosmtrek/air:latest

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# This container exposes port 8080 to the outside world
EXPOSE 8080

# Run the command
CMD ["air", "-c", ".air.conf"]